comics/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'comics'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('allcharacters/', views.allCharacters, name='allCharacters'),
    path('marvelcharacters/', views.marvelCharacters, name = 'marvelCharacters'),
    path('dccharacters/', views.dcCharacters, name = 'dcCharacters'),
    path('otherpublishers/', views.otherPublishers, name = 'otherPublishers'),
    path('results/', views.SearchResultsView.as_view(), name = "searchResults"),
    path('add/', views.addCharacter, name = 'addCharacter'),
    path('<name>/edit/', views.edit, name = 'edit'),
    path('otherpublishers/<publisher>/', views.otherCharacters, name='otherCharacters'),
    path('<name>/', views.characterInfo, name='characterInfo'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

comicswiki/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('comics/', include('comics.urls'), name = "comics"),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name = 'login.html'), name = 'login'),
    path('logout', auth_views.LogoutView.as_view(template_name = 'logout.html'), name = 'logout'),
    path('profile/', user_views.profile, name='profile'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name = 'password_reset.html')
         , name = 'password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name = 'password_reset_done.html'),
         name = 'password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name =
     'password_reset_confirm.html'), name = 'password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name =
    'password_reset_complete.html'), name = 'password_reset_complete'),
    path('users/', user_views.users, name = 'users'),
    path('users/<username>', user_views.profileInfo, name = 'profileInfo'),
    path('delete/', user_views.delete_confirm, name = 'delete_confirm'),
    path('delete_done/', user_views.delete_done, name = 'delete_done'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

comics/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class superheroPowerstats(models.Model):
    name = models.CharField(max_length = 100)
    intelligence = models.IntegerField()
    strength = models.IntegerField()
    speed = models.IntegerField()
    durability = models.IntegerField()
    power = models.IntegerField()
    combat = models.IntegerField()

class superheroAppearance(models.Model):
    name = models.CharField(max_length = 100)
    gender = models.CharField(max_length = 40)
    race = models.CharField(max_length = 60)
    height = models.CharField(max_length = 60)
    weight = models.CharField(max_length = 60)
    eyeColor = models.CharField(max_length = 40)
    hairColor = models.CharField(max_length = 40)

class superheroBiography(models.Model):
    name = models.CharField(max_length = 100)
    fullName = models.CharField(max_length = 100)
    alterEgos = models.CharField(max_length = 250)
    aliases = models.CharField(max_length = 250)
    birthPlace = models.CharField(max_length = 100)
    firstAppearance = models.CharField(max_length = 250)
    publisher = models.CharField(max_length = 100)
    alignment = models.CharField(max_length = 50, default = "neutral")


class superheroWork(models.Model):
    name = models.CharField(max_length = 100)
    occupation = models.CharField(max_length = 500)
    base = models.CharField(max_length = 250)

class superheroConnections(models.Model):
    name = models.CharField(max_length = 100)
    groupAffiliation = models.CharField(max_length = 1000)
    relatives = models.CharField(max_length = 1000)

class superheroImages(models.Model):
    name = models.CharField(max_length = 100)
    small = models.ImageField(upload_to = 'images')
    medium = models.ImageField(upload_to = 'images')
    large = models.ImageField()

comics/forms.py
from django import forms
from .models import superheroBiography, superheroAppearance, superheroWork, superheroConnections, superheroPowerstats, superheroImages

class SuperheroBiographyForm(forms.ModelForm):
    class Meta:
        model = superheroBiography
        fields = ['fullName', 'alterEgos', 'aliases', 'birthPlace', 'firstAppearance', 'publisher']

class SuperheroAppearanceForm(forms.ModelForm):
    class Meta:
        model = superheroAppearance
        fields = ['gender', 'race', 'height', 'weight', 'eyeColor', 'hairColor']

class SuperheroWorkForm(forms.ModelForm):
    class Meta:
        model = superheroWork
        fields = ['occupation', 'base']

class SuperheroConnectionsForm(forms.ModelForm):
    class Meta:
        model = superheroConnections
        fields = ['groupAffiliation', 'relatives']

class SuperheroPowerstatsForm(forms.ModelForm):
    class Meta:
        model = superheroPowerstats
        fields = ['intelligence', 'strength', 'speed', 'durability', 'power', 'combat']

class SuperheroImagesForm(forms.ModelForm):
    class Meta:
        model = superheroImages
        fields = ['medium']

class SuperheroNameForm(forms.ModelForm):
    class Meta:
        model = superheroBiography
        fields = ['name']

class SuperheroCreationForm(forms.ModelForm):
    alignment_choices = [('good', 'Hero'), ('bad', 'Villian'), ('neutral', 'Anti-hero')]
    alignment = forms.CharField(label = "What is the character's alignment?", widget = forms.Select(
        choices = alignment_choices))
    class Meta:
        model = superheroBiography
        fields = ['name', 'publisher', 'alignment']

comics/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
import requests
from .models import superheroPowerstats, superheroAppearance, superheroBiography, superheroWork, superheroConnections, superheroImages
import json
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from django.db.models import Q
from .forms import SuperheroBiographyForm, SuperheroAppearanceForm, SuperheroWorkForm, SuperheroConnectionsForm, SuperheroPowerstatsForm, SuperheroImagesForm, SuperheroNameForm, SuperheroCreationForm
# Create your views here.

def index(request):
    ironman = superheroImages.objects.filter(name = "Iron Man")
    spiderman = superheroImages.objects.filter(name = "Spider-Man")
    captain_america = superheroImages.objects.filter(name = "Captain America")
    batman = superheroImages.objects.filter(name = "Batman (Bruce Wayne)")
    superman = superheroImages.objects.filter(name = "Superman")
    wonderWoman = superheroImages.objects.filter(name = "Wonder Woman")
    darthVader = superheroImages.objects.filter(name = "Darth Vader")
    goku = superheroImages.objects.filter(name = "Goku")
    onePunchMan = superheroImages.objects.filter(name = "One Punch Man")
    return render(request, 'index.html', {'spiderman': spiderman[0], 'ironman': ironman[0], 'captain': captain_america[0],
                                          'batman': batman[0], 'superman': superman[0], 'wonderWoman': wonderWoman[0],
                                          'darthVader': darthVader[0], 'goku': goku[0], 'onePunchMan': onePunchMan[0]})

def gettingAPI():
    superheroData = []
    superheroDict = dict()
    for i in range(731):
        number = i + 1
        superhero = requests.get(f"https://akabab.github.io/superhero-api/api/id/{number}.json")
        if (superhero.status_code != 404):
            jsonSuperheroData = json.loads(superhero.text)
            if (jsonSuperheroData["biography"]["fullName"] == ""):
                jsonSuperheroData["biography"]["fullName"] = "Unknown"
            if ("III" in jsonSuperheroData["name"]):
                jsonSuperheroData["name"] = jsonSuperheroData["name"].replace("III", "(" +
                                                                              jsonSuperheroData["biography"]["fullName"]
                                                                              + ")")
            elif ("II" in jsonSuperheroData["name"]):
                jsonSuperheroData["name"] = jsonSuperheroData["name"].replace("II", "(" +
                                                                              jsonSuperheroData["biography"]["fullName"]
                                                                              + ")")
            elif (" IV" in jsonSuperheroData["name"]):
                jsonSuperheroData["name"] = jsonSuperheroData["name"].replace(" IV", " (" +
                                                                              jsonSuperheroData["biography"]["fullName"]
                                                                              + ")")
            elif ("VI" in jsonSuperheroData["name"]):
                jsonSuperheroData["name"] = jsonSuperheroData["name"].replace("VI", "(" +
                                                                              jsonSuperheroData["biography"]["fullName"]
                                                                              + ")")
            elif (" V" in jsonSuperheroData["name"] and "V" == jsonSuperheroData["name"][
                    len(jsonSuperheroData["name"]) - 1]):
                jsonSuperheroData["name"] = jsonSuperheroData["name"].replace(" V", " (" +
                                                                              jsonSuperheroData["biography"]["fullName"]
                                                                              + ")")
            if (jsonSuperheroData["name"] in superheroDict):
                superheroData[len(superheroData) - 1]["name"] = superheroData[len(superheroData) - 1]["name"] + " (" + \
                                               superheroData[len(superheroData) - 1]["biography"]["fullName"] + ")"
                jsonSuperheroData["name"] = jsonSuperheroData["name"] + " (" + jsonSuperheroData["biography"][
                    "fullName"] + ")"
            superheroDict[jsonSuperheroData["name"]] = True
            superheroData.append(jsonSuperheroData)
    return superheroData



def characterInfo(request, name):
    characterImage = superheroImages.objects.filter(name = name)
    characterAppearance = superheroAppearance.objects.filter(name = name)
    characterWork = superheroWork.objects.filter(name = name)
    characterConnections = superheroConnections.objects.filter(name = name)
    characterBiography = superheroBiography.objects.filter(name = name)
    characterPowerstats = superheroPowerstats.objects.filter(name = name)
    return render(request, 'characterInfo.html', {'biography': characterBiography[0], 'image': characterImage[0],
                                                  'appearance': characterAppearance[0], 'work': characterWork[0],
                                                  'connections': characterConnections[0], 'powerstats': characterPowerstats[0]})

def allCharacters(request):
    character_set = superheroBiography.objects.all().order_by("name")
    return render(request, 'allCharacters.html', {'characters': character_set})


def marvelCharacters(request):
    good_marvel_set = superheroBiography.objects.filter(publisher = "Marvel Comics", alignment = "good").order_by("name")
    neutral_marvel_set = superheroBiography.objects.filter(publisher="Marvel Comics", alignment="neutral").order_by("name")
    bad_marvel_set = superheroBiography.objects.filter(publisher = "Marvel Comics", alignment = "bad").order_by("name")
    return render(request, 'marvelCharacters.html', {'goodMarvelCharacters': good_marvel_set, 'neutralMarvelCharacters':
    neutral_marvel_set, 'badMarvelCharacters': bad_marvel_set})

def dcCharacters(request):
    good_dc_set = superheroBiography.objects.filter(publisher = "DC Comics", alignment = "good").order_by("name")
    neutral_dc_set = superheroBiography.objects.filter(publisher="DC Comics", alignment="neutral").order_by("name")
    bad_dc_set = superheroBiography.objects.filter(publisher = "DC Comics", alignment = "bad").order_by("name")
    return render(request, 'dcCharacters.html', {'goodDCCharacters': good_dc_set, 'neutralDCCharacters': neutral_dc_set,
                                                 'badDCCharacters': bad_dc_set})

def otherPublishers(request):
    otherPublishers = superheroBiography.objects.exclude(publisher="Marvel Comics").exclude(publisher="DC Comics").values('publisher').distinct().order_by("publisher")
    return render(request, 'otherPublishers.html', {'otherPublishers': otherPublishers})

def otherCharacters(request, publisher):
    publisherCharacters = superheroBiography.objects.filter(publisher = publisher).order_by("name")
    return render(request, 'otherCharacters.html', {'otherCharacters': publisherCharacters, 'publisher': publisher})

def createSuperhero():
    data = gettingAPI()
    for superhero in data:
        onePowerStats = superheroPowerstats(name = superhero["name"], intelligence = superhero["powerstats"]
        ["intelligence"], strength = superhero["powerstats"]["strength"], speed = superhero["powerstats"]["speed"],
                                            durability = superhero["powerstats"]["durability"], power = superhero
            ["powerstats"]["power"], combat = superhero["powerstats"]["combat"])
        if(superhero["appearance"]["race"] == None):
            race = "Unknown"
        else:
            race = superhero["appearance"]["race"]
        heightList = superhero["appearance"]["height"]
        height = ""
        for heightNumber in range(len(heightList)):
            height += heightList[heightNumber]
            if (heightNumber != len(heightList) - 1):
                height += " or "
        weightList = superhero["appearance"]["weight"]
        weight = ""
        for weightNumber in range(len(weightList)):
            weight += weightList[weightNumber]
            if (weightNumber != len(weightList) - 1):
                weight += " or "
        oneAppearance = superheroAppearance(name = superhero["name"], gender = superhero["appearance"]["gender"], race =
                                            race, height = height, weight = weight, eyeColor =
                                            superhero["appearance"]["eyeColor"], hairColor = superhero["appearance"]["hairColor"])
        aliasList = superhero["biography"]["aliases"]
        aliases = ""
        for aliasNumber in range(len(aliasList)):
            aliases += aliasList[aliasNumber]
            if (aliasNumber != len(aliasList) - 1):
                aliases += ", "
        if(superhero["biography"]["publisher"] == None):
            publisher = ""
        else:
            publisher = superhero["biography"]["publisher"]
        oneBiography = superheroBiography(name = superhero["name"], fullName = superhero["biography"]["fullName"],
                                          alterEgos = superhero["biography"]["alterEgos"], aliases = aliases,
                                          birthPlace = superhero["biography"]["placeOfBirth"], firstAppearance =
                                          superhero["biography"]["firstAppearance"], publisher = publisher, alignment = superhero["biography"]["alignment"])
        oneWork = superheroWork(name = superhero["name"], occupation = superhero["work"]["occupation"], base = superhero
                                ["work"]["base"])
        oneConnection = superheroConnections(name = superhero["name"], groupAffiliation = superhero["connections"]
        ["groupAffiliation"], relatives = superhero["connections"]["relatives"])

templates/comics/addCharacter.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
<div style="min-height: 100vh; font-family: Garamond, serif; color: black !important;">
    <form method = "POST">
        {% csrf_token %}
        <fieldset class = "form-group">
            <legend class = "border-bottom mb-4" style = "font-weight: bold">Create a New Character Page</legend>
            {{ character|crispy }}
        </fieldset>
        <div class = "form-group">
            <button class = "btn btn-outline-info" type = "submit">Create</button>
        </div>
    </form>
</div>
{% endblock %}

templates/comics/allCharacters.html
{% extends "base.html" %}
{% block content %}
<div style="min-height: 1000vh;">
    <div class="text-decoration-underline" style = "font-family: Garamond, serif; font-size: 40px; text-align: center; ">
    Characters
</div>
    <div class = "accordion-body" style = "text-align: center; font-family: Garamond, serif; font-size: 22px; ">
        <a href="/comics/add" class = "text-decoration-none">
            Add a Character
    </a>
        </div>
    <div class="text-md-left" style = "font-family: Garamond, serif; font-size: 30px; text-align: center">
    &nbsp
</div>
 <div class="row">
    {% for character in characters %}
    <div class="col-sm-3 mb-3">
<div class="text-md-left" style = "font-family: Garamond, serif; font-size: 20px">
    <a href="/comics/{{character.name}}" class="text-decoration-none">
            {{character.name}}
    </a>
</div>
    </div>

    {% endfor %}
 </div>
</div>
{% endblock %}

templates/comics/base.html
<!DOCTYPE html>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

{% load static %}

<link rel="stylesheet" href="{% static 'users/style.css' %}">

<div class="background container-fluid" style="overflow: hidden; background: #DC143C; background: -webkit-linear-gradient(to right, #DC143C, #8B0000); background: linear-gradient(to right, #DC143C, #8B0000);">
  <nav class="navbar navbar-expand navbar-light navbar border border-dark    " style="border-radius: 10px; border-color:black">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="{% url 'comics:index' %}" style = "font-family: Garamond" >Comics Universal</a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'comics:index' %}" style = "font-family: Garamond" >Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'comics:allCharacters' %}" style = "font-family: Garamond" >All Characters</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'comics:marvelCharacters' %}" style = "font-family: Garamond" >Marvel Comics</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'comics:dcCharacters' %}" style = "font-family: Garamond" >DC Comics</a>
      </li>
         <li class="nav-item">
        <a class="nav-link" href="{% url 'comics:otherPublishers'%}" style = "font-family: Garamond" >Other Comic Publishers</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action = "{% url 'comics:searchResults' %}", method = "get">
           <div class="input-group mb-1">
                    <input name = "result" type="text" class="form-control"
                      placeholder="Search">
                   <button class="btn btn-dark"
                     type="submit"
                     id="addon-btn" formaction = "{% url 'comics:searchResults' %}">
                     Search
                   </button>
          </div>
</form>
       <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
           {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profile' %}" style = "font-family: Garamond" >Profile</a>
            </li>
           <li class = "nav-item">
               <a class = "nav-link" href="{% url 'logout' %}" style = "font-family: Garamond">Logout</a>
           </li>
           {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}" style = "font-family: Garamond" >Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}" style = "font-family: Garamond" >Register</a>
            </li>

           {% endif %}
           <li class="nav-item">
                <a class="nav-link" href="{% url 'users' %}" style = "font-family: Garamond" >Users</a>
            </li>
       </ul>

  </div>
</nav>
    <head>
        {% block header %}
        {% endblock %}
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
    <footer>
        <div style = "font-family: Garamond, serif; text-align: center;font-size: 17px; font-weight: bold">
            Created by Connor Goodall With The Help of
            <a href = "https://github.com/akabab/superhero-api" class = "text-decoration-none">
                Superhero API
                </a>
                and
            <a href = " https://www.devhandbook.com" class = "text-decoration-none">
            Dev Handbook
            </a>

        </div>
        {% block footer %}
        {% endblock %}
    </footer>
</div>

templates/comics/characterInfo.html
{% extends "base.html" %}
{% block content %}
<div style="min-height: 100vh; overflow-x:hidden;">
    <div class="accordion-body" style = "text-align: center; font-family: Garamond, serif; font-size: 40px">
        {{biography.name}}
    </div>
    <div class = "accordion-body" style = "text-align: center; font-family: Garamond, serif; font-size: 25px; ">
        <a href="/comics/{{biography.name}}/edit" class = "text-decoration-none">
            Edit
    </a>
    </div>
    <img class = "accordion-body" style="border-radius: 15%; margin-right: 2.5%; float: right" src= {{image.medium.url}} onError = "this.src = '{{image.medium}}'" width="300" height="350">
    <div class="text-md-left" style = "font-family: Garamond, serif; font-size: 30px; font-weight: bold">
        Biography
     </div>
    <div class="text-md-left" style = "font-family: Garamond, serif; font-size: 20px">
         Full Name: {{biography.fullName}}
        <br> Alter Egos: {{biography.alterEgos}}
        <br> Aliases: {{biography.aliases}}
        <br> Birth Place: {{biography.birthPlace}}
        <br> First Appearance: {{biography.firstAppearance}}
        <br> Publisher: {{biography.publisher}}
        <br>
    </div>
    <div class="text-md-left" style = "font-family: Garamond, serif; font-size: 30px; font-weight: bold">
        Appearance
     </div>
    <div class="text-md-left" style = "font-family: Garamond, serif; font-size: 20px">
        Gender: {{appearance.gender}}
        <br> Race: {{appearance.race}}
        <br> Height: {{appearance.height}}
        <br> Weight: {{appearance.weight}}
        <br> Eye Color: {{appearance.eyeColor}}
        <br> Hair Color: {{appearance.hairColor}}
        <br>
    </div>
    <div class="text-md-left" style = "font-family: Garamond, serif; font-size: 30px; font-weight: bold">
        Work
     </div>
    <div class="text-md-left" style = "font-family: Garamond, serif; font-size: 20px">
        Occupation: {{work.occupation}}
        <br> Base: {{work.base}}
        <br>
    </div>
    <div class="text-md-left" style = "font-family: Garamond, serif; font-size: 30px; font-weight: bold">
        Connections
    </div>
    <div class="text-md-left" style = "font-family: Garamond, serif; font-size: 20px">
        Group Affiliations: {{connections.groupAffiliation}}
        <br> Relatives: {{connections.relatives}}
    </div>
    <div class="text-md-left" style = "font-family: Garamond, serif; font-size: 30px; font-weight: bold">
        Powerstats
    </div>
    <table class="table table-bordered" style="border-color:black">
        <thead>
        <tr>
            <th scope="col">Powerstats</th>
            <th scope="col">Number</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row">Intelligence</th>
            <td>{{powerstats.intelligence}}</td>
        </tr>
        <tr>
            <th scope="row">Strength</th>
            <td>{{powerstats.strength}}</td>
        </tr>
        <tr>
            <th scope="row">Speed</th>
            <td>{{powerstats.speed}}</td>
        </tr>
        <tr>
            <th scope="row">Durability</th>
            <td>{{powerstats.durability}}</td>
        </tr>
        <tr>
            <th scope="row">Power</th>
            <td>{{powerstats.power}}</td>
        </tr>
        <tr>
            <th scope="row">Combat</th>
            <td>{{powerstats.combat}}</td>
        </tr>
        </tbody>
    </table>
</div>
{% endblock %}

templates/comics/dcCharacters.html
{% extends "base.html" %}
{% block content %}
<div style="min-height: 100vh;">
    <div class="text-decoration-underline" style = "font-family: Garamond, serif; font-size: 40px; text-align: center;">
    DC Characters
</div>
     <div class = "accordion-body" style = "text-align: center; font-family: Garamond, serif; font-size: 22px; ">
        <a href="/comics/add" class = "text-decoration-none">
            Add a DC Character
        </a>
     </div>
    <div class="text-md-left" style = "font-family: Garamond, serif; font-size: 40px; text-align: center">
        &nbsp
    </div>
     <div class="container">
        <div class="row">
            <div class="col-sm">
                <div class="text-decoration-underline" style = "font-family: Garamond, serif; font-size: 30px;">
                    Heroes
                </div>
                <div class="col" style = "display: inline-block;">
                {% for goodCharacter in goodDCCharacters %}
                    <div class="text-md-start" style = "font-family: Garamond, serif; font-size: 20px; ">
                        <a href="/comics/{{goodCharacter.name}}" class = "text-decoration-none">
                            {{goodCharacter.name}}
                        </a>

                    </div>
                {% endfor %}
                </div>
            </div>
            <div class = "col-sm">
                <div class="text-decoration-underline" style = "font-family: Garamond, serif; font-size: 30px;">
                    Anti-Heroes
                </div>
                <div class = "col" style = "display: inline-block;">
                    {% for neutralCharacter in neutralDCCharacters %}
                    <div class="text-md-start" style = "font-family: Garamond, serif; font-size: 20px;">
                      <a href="/comics/{{neutralCharacter.name}}" class = "text-decoration-none">
                            {{neutralCharacter.name}}
                         </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-sm">
                <div class="text-decoration-underline" style = "font-family: Garamond, serif; font-size: 30px;">
                    Villians
                </div>
                <div class="col" style = "display: inline-block;">
                {% for badCharacter in badDCCharacters %}
                     <div class="text-md-start" style = "font-family: Garamond, serif; font-size: 20px;">
                         <a href="/comics/{{badCharacter.name}}" class = "text-decoration-none">
                            {{badCharacter.name}}
                         </a>

                    </div>
                {% endfor %}
                </div>
            </div>
        </div>
     </div>
</div>
{% endblock %}

templates/comics/edit.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
<div style="min-height: 100vh; font-family: Garamond, serif; color: black !important;">
    <form method = "POST" enctype = "multipart/form-data">
        {% csrf_token %}
        <fieldset class = "form-group">
            <legend class = "border-bottom mb-4" style = "font-weight: bold">Name</legend>
            {{ sn_form|crispy }}
            <legend class = "border-bottom mb-4" style = "font-weight: bold">Image</legend>
            {{ image_form|crispy }}
            <legend class = "border-bottom mb-4" style = "font-weight: bold">Biography</legend>
            {{ sb_form|crispy }}
            <legend class = "border-bottom mb-4" style = "font-weight: bold">Appearance</legend>
            {{ sa_form|crispy }}
            <legend class = "border-bottom mb-4" style = "font-weight: bold">Work</legend>
            {{ sw_form|crispy }}
            <legend class = "border-bottom mb-4" style = "font-weight: bold">Connections</legend>
            {{ sc_form|crispy }}
            <legend class = "border-bottom mb-4" style = "font-weight: bold">Powerstats</legend>
            {{ sp_form|crispy }}
        </fieldset>
        <div class = "form-group">
            <button class = "btn btn-outline-info" type = "submit">Update</button>
        </div>
    </form>
</div>
{% endblock %}

templates/comics/searchResults.html
{% extends "base.html" %}
{% block content %}
<div style="min-height: 100vh;">
    <h1 style = "font-family: Garamond, serif; font-size: 40px; text-align: center ">Search Results</h1>
    <div class="text-md-left" style = "font-family: Garamond, serif; font-size: 40px; text-align: center">
    &nbsp
</div>
    <ul>
<div class = "row">
{% for superhero in object_list %}
    <div class="col-sm-3 mb-3">
        <img class = "accordion-body" style="border-radius: 15%;" src= {{superhero.medium.url}} onError = "this.src = '{{superhero.medium}}'" width="200" height="250">
        <div class="text-md-left" style = "font-family: Garamond, serif; font-size: 30px;">
    <a href="/comics/{{superhero.name}}" class = "text-decoration-none">
            {{superhero.name}}
    </a>
        </div>
    </div>
{% endfor %}
</div>
    </ul>
</div>
{% endblock %}